// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3619fa03-e62c-4fec-9de8-e69077f25331",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rBklrZgYa",
    "aws_user_pools_web_client_id": "6e5nonpc482ls9a9ahrrsmn8me",
    "aws_user_files_s3_bucket": "awsamplifyvuetest1367426f2469468495ef1641a499fae4",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
